### ISSUE TITLE
ModuleNotFoundError: No module named 'httpx'

### ISSUE THREAD

**Issue by cpylua** [simonw/llm-openrouter#3]
It looks like I have to install `httpx` first, otherwise running `llm` after installing `llm-openrouter` throws an error `ModuleNotFoundError: No module named 'httpx'`.

`llm, version 0.8`

**Comment by alexclaydon** [comment]
Hello, yes I'm in the same boat here.  MacOS 13.5, installed LLM using `brew`.

**Comment by motin** [comment]
Same here, but installed pipx via brew and llm via pipx Stack trace:

```
$ llm install llm-openrouter
Collecting llm-openrouter
  Downloading llm_openrouter-0.1-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: llm>=0.8 in /Users/motin/.local/pipx/venvs/llm/lib/python3.12/site-packages (from llm-openrouter) (0.12)
Requirement already satisfied: click in /Users/motin/.local/pipx/venvs/llm/lib/python3.12/site-packages (from llm>=0.8->llm-openrouter) (8.1.7)
Requirement already satisfied: openai<1.0 in /Users/motin/.local/pipx/venvs/llm/lib/python3.12/site-packages (from llm>=0.8->llm-openrouter) (0.28.1)
Requirement already satisfied: click-default-group>=1.2.3 in /Users/motin/.local/pipx/venvs/llm/lib/python3.12/site-packages (from llm>=0.8->llm-openrouter) (1.2.4)
Requirement already satisfied: sqlite-utils>=3.35.0 in /Users/motin/.local/pipx/venvs/llm/lib/python3.12/site-packages (from llm>=0.8->llm-openrouter) (3.35.2)
Requirement already satisfied: sqlite-migrate>=0.1a2 in /Users/motin/.local/pipx/venvs/llm/lib/python3.12/site-packages (from llm>=0.8->llm-openrouter) (0.1b0)
Requirement already satisfied: pydantic>=1.10.2 in /Users/motin/.local/pipx/venvs/llm/lib/python3.12/site-packages (from llm>=0.8->llm-openrouter) (2.5.2)
Requirement already satisfied: PyYAML in /Users/motin/.local/pipx/venvs/llm/lib/python3.12/site-packages (from llm>=0.8->llm-openrouter) (6.0.1)
Requirement already satisfied: pluggy in /Users/motin/.local/pipx/venvs/llm/lib/python3.12/site-packages (from llm>=0.8->llm-openrouter) (1.3.0)
Requirement already satisfied: python-ulid in /Users/motin/.local/pipx/venvs/llm/lib/python3.12/site-packages (from llm>=0.8->llm-openrouter) (2.2.0)
Requirement already satisfied: setuptools in /Users/motin/.local/pipx/shared/lib/python3.12/site-packages (from llm>=0.8->llm-openrouter) (69.0.2)
Requirement already satisfied: pip in /Users/motin/.local/pipx/shared/lib/python3.12/site-packages (from llm>=0.8->llm-openrouter) (23.3.1)
Requirement already satisfied: requests>=2.20 in /Users/motin/.local/pipx/venvs/llm/lib/python3.12/site-packages (from openai<1.0->llm>=0.8->llm-openrouter) (2.31.0)
Requirement already satisfied: tqdm in /Users/motin/.local/pipx/venvs/llm/lib/python3.12/site-packages (from openai<1.0->llm>=0.8->llm-openrouter) (4.66.1)
Requirement already satisfied: aiohttp in /Users/motin/.local/pipx/venvs/llm/lib/python3.12/site-packages (from openai<1.0->llm>=0.8->llm-openrouter) (3.9.1)
Requirement already satisfied: annotated-types>=0.4.0 in /Users/motin/.local/pipx/venvs/llm/lib/python3.12/site-packages (from pydantic>=1.10.2->llm>=0.8->llm-openrouter) (0.6.0)
Requirement already satisfied: pydantic-core==2.14.5 in /Users/motin/.local/pipx/venvs/llm/lib/python3.12/site-packages (from pydantic>=1.10.2->llm>=0.8->llm-openrouter) (2.14.5)
Requirement already satisfied: typing-extensions>=4.6.1 in /Users/motin/.local/pipx/venvs/llm/lib/python3.12/site-packages (from pydantic>=1.10.2->llm>=0.8->llm-openrouter) (4.8.0)
Requirement already satisfied: sqlite-fts4 in /Users/motin/.local/pipx/venvs/llm/lib/python3.12/site-packages (from sqlite-utils>=3.35.0->llm>=0.8->llm-openrouter) (1.0.3)
Requirement already satisfied: tabulate in /Users/motin/.local/pipx/venvs/llm/lib/python3.12/site-packages (from sqlite-utils>=3.35.0->llm>=0.8->llm-openrouter) (0.9.0)
Requirement already satisfied: python-dateutil in /Users/motin/.local/pipx/venvs/llm/lib/python3.12/site-packages (from sqlite-utils>=3.35.0->llm>=0.8->llm-openrouter) (2.8.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/motin/.local/pipx/venvs/llm/lib/python3.12/site-packages (from requests>=2.20->openai<1.0->llm>=0.8->llm-openrouter) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/motin/.local/pipx/venvs/llm/lib/python3.12/site-packages (from requests>=2.20->openai<1.0->llm>=0.8->llm-openrouter) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/motin/.local/pipx/venvs/llm/lib/python3.12/site-packages (from requests>=2.20->openai<1.0->llm>=0.8->llm-openrouter) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/motin/.local/pipx/venvs/llm/lib/python3.12/site-packages (from requests>=2.20->openai<1.0->llm>=0.8->llm-openrouter) (2023.11.17)
Requirement already satisfied: attrs>=17.3.0 in /Users/motin/.local/pipx/venvs/llm/lib/python3.12/site-packages (from aiohttp->openai<1.0->llm>=0.8->llm-openrouter) (23.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/motin/.local/pipx/venvs/llm/lib/python3.12/site-packages (from aiohttp->openai<1.0->llm>=0.8->llm-openrouter) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in /Users/motin/.local/pipx/venvs/llm/lib/python3.12/site-packages (from aiohttp->openai<1.0->llm>=0.8->llm-openrouter) (1.9.3)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/motin/.local/pipx/venvs/llm/lib/python3.12/site-packages (from aiohttp->openai<1.0->llm>=0.8->llm-openrouter) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in /Users/motin/.local/pipx/venvs/llm/lib/python3.12/site-packages (from aiohttp->openai<1.0->llm>=0.8->llm-openrouter) (1.3.1)
Requirement already satisfied: six>=1.5 in /Users/motin/.local/pipx/venvs/llm/lib/python3.12/site-packages (from python-dateutil->sqlite-utils>=3.35.0->llm>=0.8->llm-openrouter) (1.16.0)
Downloading llm_openrouter-0.1-py3-none-any.whl (7.6 kB)
Installing collected packages: llm-openrouter
Successfully installed llm-openrouter-0.1
motin-mbp21:lazy motin$ llm models list
Traceback (most recent call last):
  File "/Users/motin/.local/bin/llm", line 5, in <module>
    from llm.cli import cli
  File "/Users/motin/.local/pipx/venvs/llm/lib/python3.12/site-packages/llm/__init__.py", line 18, in <module>
    from .plugins import pm
  File "/Users/motin/.local/pipx/venvs/llm/lib/python3.12/site-packages/llm/plugins.py", line 17, in <module>
    pm.load_setuptools_entrypoints("llm")
  File "/Users/motin/.local/pipx/venvs/llm/lib/python3.12/site-packages/pluggy/_manager.py", line 398, in load_setuptools_entrypoints
    plugin = ep.load()
             ^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.0/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.0/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/motin/.local/pipx/venvs/llm/lib/python3.12/site-packages/llm_openrouter.py", line 6, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'
```

Can we get https://github.com/simonw/llm-openrouter/pull/4 merged to fix this?

**Comment by simonw** [comment]
Fixed in:
- #4
