### ISSUE TITLE
This stopped working and now throws `No module named 'urllib3'`

### ISSUE THREAD

**Issue by ibehnam** [simonw/llm-openrouter#9]
This used to work until about a month ago when it suddenly stopped working. This is the error I'm getting:

```
✨ llm keys set openrouter                                                                                                                  18:20:45
Traceback (most recent call last):
  File "/opt/homebrew/bin/llm", line 5, in <module>
    from llm.cli import cli
  File "/opt/homebrew/Cellar/llm/0.13.1_1/libexec/lib/python3.12/site-packages/llm/__init__.py", line 18, in <module>
    from .plugins import pm
  File "/opt/homebrew/Cellar/llm/0.13.1_1/libexec/lib/python3.12/site-packages/llm/plugins.py", line 17, in <module>
    pm.load_setuptools_entrypoints("llm")
  File "/opt/homebrew/Cellar/llm/0.13.1_1/libexec/lib/python3.12/site-packages/pluggy/_manager.py", line 414, in load_setuptools_entrypoints
    plugin = ep.load()
             ^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/llm/0.13.1_1/libexec/lib/python3.12/site-packages/llm_openrouter.py", line 7, in <module>
    import urllib3
ModuleNotFoundError: No module named 'urllib3'
```

**Comment by ibehnam** [comment]
Solved by `llm install urllib3`. Didn't know we could install Python dependencies through `llm`, but your workaround regarding Homebrew limitations made me think of this solution. `pipx` wouldn't let me install `urllib3`, saying that it's not a dependency for any package.

**Comment by simonw** [comment]
Thanks for the bug report, maybe this is a Python 3.12 thing? I'll add `urllib3` as a direct dependency (once I recreate the bug).

**Comment by ibehnam** [comment]
@simonw Yes, it's Python 3.12. The bug actually was worse than I thought because once it happens, also messes with the other functionality of `llm` as well. Had to `pipx uninstall` it a few times as it wouldn't let me set the API keys either.

**Comment by simonw** [comment]
Actually I had a fix for this already, I just hadn't pushed it yet.
